services:
  namenode:
    build: .
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    build: .
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  resourcemanager:
    build: .
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      - namenode

  hive-metastore:
    build: .
    container_name: hive-metastore
    command: /opt/hive/bin/hive --service metastore
    depends_on:
      - hive-metastore-postgresql

  hive-server:
    build: .
    container_name: hive-server
    ports:
      - "10000:10000"
    command: /opt/hive/bin/hive --service hiveserver2
    depends_on:
      - hive-metastore

  hive-metastore-postgresql:
    image: postgres:15-alpine
    container_name: hive-metastore-postgresql
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_HOST_AUTH_METHOD: md5
      
volumes:
  hadoop_namenode:
  hadoop_datanode:
